DEBUG 2024-04-23 00:43:53.596 UTC: 	 CRAB Client version: v3.240110
DEBUG 2024-04-23 00:43:53.596 UTC: 	 Running on: Linux lxplus803.cern.ch 4.18.0-513.24.1.el8_9.x86_64 #1 SMP Thu Mar 14 14:20:09 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux - Red Hat Enterprise Linux 8.9 (Ootpa)
DEBUG 2024-04-23 00:43:53.596 UTC: 	 Executing command: 'submit'
DEBUG 2024-04-23 00:43:53.596 UTC: 	 Found CRAB cache file /afs/cern.ch/user/r/rpradhan/.crab3
INFO 2024-04-23 00:43:53.597 UTC: 	 Will use CRAB configuration file crab_config_MCRecoDebug.py
DEBUG 2024-04-23 00:43:53.597 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-04-23 00:43:53.600 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-04-23 00:43:53.600 UTC: 	 Working area '/afs/cern.ch/work/r/rpradhan/Tracking_Studies/newCode_AfterRun3/ForEffTest/CMSSW_13_2_5_patch1/src/Analyzers/RaghuEffTest/crab/TrackingStudies_Run3/crab_GeneralTracks_MAOD_effCorrectionTest_V1' already exists 
Please change the requestName in the config file
ERROR 2024-04-23 00:43:53.600 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/lib/CRABClient/Commands/SubCommand.py", line 327, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240110.01/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/afs/cern.ch/work/r/rpradhan/Tracking_Studies/newCode_AfterRun3/ForEffTest/CMSSW_13_2_5_patch1/src/Analyzers/RaghuEffTest/crab/TrackingStudies_Run3/crab_GeneralTracks_MAOD_effCorrectionTest_V1' already exists 
Please change the requestName in the config file
INFO 2024-04-23 00:43:53.603 UTC: 	 Log file is /afs/cern.ch/work/r/rpradhan/Tracking_Studies/newCode_AfterRun3/ForEffTest/CMSSW_13_2_5_patch1/src/Analyzers/RaghuEffTest/crab/crab.log
DEBUG 2024-10-19 22:05:25.483 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-10-19 22:05:25.483 UTC: 	 Running on: Linux lxplus819.cern.ch 4.18.0-553.16.1.el8_10.x86_64 #1 SMP Thu Aug 1 04:16:12 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux - Red Hat Enterprise Linux 8.10 (Ootpa)
DEBUG 2024-10-19 22:05:25.483 UTC: 	 Executing command: 'submit'
DEBUG 2024-10-19 22:05:25.499 UTC: 	 Found CRAB cache file /afs/cern.ch/user/r/rpradhan/.crab3
INFO 2024-10-19 22:05:25.722 UTC: 	 Will use CRAB configuration file crab_config_MCRecoDebug.py
DEBUG 2024-10-19 22:05:25.722 UTC: 	 Loading CRAB configuration file.
ERROR 2024-10-19 22:05:25.729 UTC: 	 Invalid CRAB configuration: Parameter General.requestName should not be longer than 100 characters.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2024-10-19 22:05:25.729 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 325, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 96, in loadConfig
    raise ConfigurationException(configmsg)
CRABClient.ClientExceptions.ConfigurationException: Invalid CRAB configuration: Parameter General.requestName should not be longer than 100 characters.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2024-10-19 22:05:25.732 UTC: 	 Log file is /afs/cern.ch/work/r/rpradhan/Tracking_Studies/newCode_AfterRun3/ForEffTest/CMSSW_13_2_10/src/Analyzers/RaghuEffTest/crab/crab.log
DEBUG 2024-10-19 22:06:17.326 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-10-19 22:06:17.327 UTC: 	 Running on: Linux lxplus819.cern.ch 4.18.0-553.16.1.el8_10.x86_64 #1 SMP Thu Aug 1 04:16:12 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux - Red Hat Enterprise Linux 8.10 (Ootpa)
DEBUG 2024-10-19 22:06:17.327 UTC: 	 Executing command: 'submit'
DEBUG 2024-10-19 22:06:17.327 UTC: 	 Found CRAB cache file /afs/cern.ch/user/r/rpradhan/.crab3
INFO 2024-10-19 22:06:17.328 UTC: 	 Will use CRAB configuration file crab_config_MCRecoDebug.py
DEBUG 2024-10-19 22:06:17.328 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-10-19 22:06:17.333 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-10-19 22:06:17.333 UTC: 	 Invalid CRAB configuration: A local DBS instance 'phys03' was specified for reading an input dataset of tier None.
Datasets of tier different than USER must be read from the global DBS instance; this is, set Data.inputDBS = 'global'.
If Data.inputDBS would not be specified, the default 'global' ('https://cmsweb.cern.ch/dbs/prod/global/DBSReader') would be used.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2024-10-19 22:06:17.333 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 325, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 96, in loadConfig
    raise ConfigurationException(configmsg)
CRABClient.ClientExceptions.ConfigurationException: Invalid CRAB configuration: A local DBS instance 'phys03' was specified for reading an input dataset of tier None.
Datasets of tier different than USER must be read from the global DBS instance; this is, set Data.inputDBS = 'global'.
If Data.inputDBS would not be specified, the default 'global' ('https://cmsweb.cern.ch/dbs/prod/global/DBSReader') would be used.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2024-10-19 22:06:17.335 UTC: 	 Log file is /afs/cern.ch/work/r/rpradhan/Tracking_Studies/newCode_AfterRun3/ForEffTest/CMSSW_13_2_10/src/Analyzers/RaghuEffTest/crab/crab.log
